# CHANGEME: Set these variable to your liking
title: ESPHome RGBW KASB10RE27HA
description: Kogan 10W Ambient 1050lm RGBW Bulb
theme: jekyll-theme-slate

# Does this just appear in the yaml file after adopting? because that would be great!
