# These substitutions allow the end user to override certain values
substitutions:
  name: "kogan-rgbw"
  friendly_name: "Kogan RGWB"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: ned.kogan-rgbw
    version: "1.0"

esp8266:
  board: esp01_1m

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://neilvangeffen/ESPHome-KASB10RE27HA/project-template-KASB10RE27HA.yaml@main

wifi:
  # Set up a wifi access point
  ap:
    password: "12345678"

# Web server is a nice thing to be able to login and look at status/upload firmware etc
web_server: 
  port: 80

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"   # API Status of the device

text_sensor:
  - platform: version
    name: "${friendly_name} ESPHome Version"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"

sm16716:
  data_pin: GPIO14
  clock_pin: GPIO4
  num_channels: 3
  num_chips: 1

output:
  - platform: sm16716
    id: output_red
    channel: 2
  - platform: sm16716
    id: output_green
    channel: 1
  - platform: sm16716
    id: output_blue
    channel: 0
  - platform: esp8266_pwm
    id: output_white
    pin: GPIO5

light:
  - platform: rgbw
    name: "${friendly_name}"
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    restore_mode: RESTORE_DEFAULT_ON 
