name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: project-template-KASB10RE27HA.yaml
      # CHANGEME: Set the name of your project here:
      name: Kogan 10W Ambient 1050lm RGBW Bulb (KASB10RE27HA)
